name: flutter_sandbox
description: Base app for experimenting

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  auto_route: ^2.3.0
  flutter_portal: ^0.4.0
  gap: ^2.0.0
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  injectable: ^1.2.2
  json_serializable: ^5.0.0
  stacked: ^2.2.5
  stacked_hooks: ^0.2.1
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  auto_route_generator: ^2.3.0
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.3
  hive_generator: ^1.1.0
  injectable_generator: ^1.3.0
  json_annotation: ^4.1.0


flutter:
  uses-material-design: true


